definitions:
  request.LoginRequest:
    properties:
      captcha:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - captcha
    - password
    - username
    type: object
  response.LoginResponse:
    properties:
      message:
        type: string
      token:
        type: string
      userInfo:
        $ref: '#/definitions/response.UserInfo'
    type: object
  response.UserInfo:
    properties:
      avatar:
        type: string
      email:
        type: string
      userId:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /captcha:
    get:
      description: 获取验证码接口
      produces:
      - image/png
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: 获取验证码
      tags:
      - Captcha
  /login:
    post:
      consumes:
      - application/json
      description: 管理登录接口，用户可以通过该接口进行登录。登录时需要提供用户名、密码和验证码。接口会校验用户的合法性、密码和验证码，如果校验成功，则生成
        JWT token 并返回。如果校验失败，则返回相应的错误信息。
      parameters:
      - description: 登录请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功，返回用户信息和 JWT token
          schema:
            $ref: '#/definitions/response.LoginResponse'
        "400":
          description: 参数错误，返回详细错误信息
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 用户认证失败，包括用户名不存在、密码错误或验证码错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误，返回详细错误信息
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: 登录
      tags:
      - Login
swagger: "2.0"
